### ISSUE TITLE
Undefined Symbol

### ISSUE THREAD

**Issue by MaxAndolini** [YashasSamaga/SmartCMD#1]
cmd_yourcommand(cid_yourcommand, playerid, "");

cid_yourcommand undefined symbol.

**Comment by YashasSamaga** [comment]
It is an issue with scope. I am looking for a workaround. For the time being, declare the command before you use the id variables.

**Comment by MaxAndolini** [comment]
How to use GetCommandID?

**Comment by MaxAndolini** [comment]
Work.

cmd_yourcommand(GetCommandID("yourcommand"), playerid, "");
