### ISSUE TITLE
1 character command

### ISSUE THREAD

**Issue by MaxAndolini** [YashasSamaga/SmartCMD#4]
error 035: argument type mismatch (argument 2)

COMMAND:v(playerid, params[]) {
return 1;
}

cmd_v(GetCommandID("v"), playerid, ""); // Bug is here.

**Comment by Banditul** [comment]
The correct syntax is 
COMMAND:v(cmdid,playerid, params[]) 
If i remember correctly

**Comment by YashasSamaga** [comment]
If you are trying to convert ZCMD compatible code to SmartCMD code, you can do it within a minute.

Read _How to upgrade from ZCMD to SmartCMD_ section in the [forum topic](http://forum.sa-mp.com/showthread.php?p=3786819).

**Comment by MaxAndolini** [comment]
My fault. Closed.
